### ISSUE TITLE
Small question about blocklists

### ISSUE THREAD

**Issue by TheDanikReal** [Alon-L/dns-adblocker#1]
Can i get list of blocklists and filters which your adblocker uses?

**Comment by TheDanikReal** [comment]
Nevermind, found in source code that this adblocker uses hagezi's dns adblocking lists
And is there any information on how much resources this thing uses? (is it suitable to run it on low-end machine for network wide filtering, etc)

**Comment by Alon-L** [comment]
Hello. I'm currently running it on a Raspberry Pi 3B+ (1GB RAM) and it seems to take around 100MB of RAM when idle, and a few hundreds more when loading the entire list of domains.
I should patch the domain fetching process in the future in order to make it consume less memory.

**Comment by TheDanikReal** [comment]
Ok, thanks for information
